# Name for this run. Except for processed catalogs, which are saved in
# catalogs/processed, and trained models, which are saved in models,
# all the results will be saved in results/run_name
run_name: lssty10+euclid # str

# -------------------------
# settings for the catalog
# -------------------------
catalog:
  name: lssty10+euclid

  # lyman alpha extinction in u band
  lya_extinction:
    seed: 42
    z_min: 1.63
    z_max: 2.36
    gamma: 2.7
    NHI_min: 12.5
    NHI_max: 17
    beta: -1.46
    b_mu: 30
    b_sig: 12
    b_min: 24
    b_max: 1000
    N_bs: 100000
    N_clouds: null

  # photometric errors
  error_model: # error model from https://arxiv.org/abs/0805.2366
    # params shared by both telescopes
    magLim: 30.0 # dimmest magnitude allowed; dimmer mags set to ndFlag
    ndFlag: 99 # flag for non-detections
    highSNR: False
    seed: 0

    # params for LSST errors
    lsst:
      tvis: 30.0 # exposure time for single visit in seconds
      nYrObs: 10.0 # number of years of observations
      nVisYr: # mean number of visits per year in each filter
        u: 5.6
        g: 8.0
        r: 18.4
        i: 18.4
        z: 16.0
        y: 16.0
      gamma: # band dependent error parameter
        u: 0.038
        g: 0.039
        r: 0.039
        i: 0.039
        z: 0.039
        y: 0.039
      airmass: 1.2 # fiducial airmass
      extendedSource: 0.0 # constant added to m5 for extended sources
      sigmaSys: 0.005 # expected irreducible error
      Cm: # band dependent parameter
        u: 23.09
        g: 24.42
        r: 24.44
        i: 24.32
        z: 24.16
        y: 23.73
      msky: # median zenith sky brightness at Cerro Pachon
        u: 22.99
        g: 22.26
        r: 21.20
        i: 20.48
        z: 19.60
        y: 18.61
      theta: # median zenith seeing FWHM, arcseconds
        u: 0.81
        g: 0.77
        r: 0.73
        i: 0.71
        z: 0.69
        y: 0.68
      km: # atmospheric extinction (T2)
        u: 0.491
        g: 0.213
        r: 0.126
        i: 0.096
        z: 0.069
        y: 0.170

    # params for Euclid errors
    euclid:
      bandNames:
        ey: ey
        j: j
        h: h
      nYrObs: 1.0 # assume Euclid is point-and-stare, so don't coadd
      nVisYr: # assume Euclid is point-and-stare, so don't coadd
        ey: 1.0
        j: 1.0
        h: 1.0
      m5: # coadded 5-sig limiting mags, from https://arxiv.org/abs/2004.07885
        ey: 24.0
        j: 24.2
        h: 23.9
      gamma: # band dependent err param, from https://arxiv.org/abs/2004.07885
        ey: 0.04
        j: 0.04
        h: 0.04
      sigmaSys: 0.005 # expected irreducible error

  # apply minimum SNR cuts
  SNR_cuts:
    u: 1.0
    g: 1.0
    r: 1.0
    i: 5.0
    z: 1.0
    y: 1.0
    ey: 1.0
    j: 1.0
    h: 1.0
