--- # -------------------------
# -------------------------
# settings for the catalog
catalog:
  name: lssty10+euclid

  # lyman alpha extinction in u band
  lya_extinction:
    z_min: 1.63
    z_max: 2.36
    gamma: 2.7
    logNHI_min: 12.5
    logNHI_max: 17
    beta: -1.46
    b_mu: 30
    b_sig: 12
    b_min: 24
    b_max: 1000
    N_bs: 100_000
    N_clouds: null # null = None, which means the default value is used

  # photometric errors
  error_model: # error model from https://arxiv.org/abs/0805.2366
    # params for LSST errors
    lsst:
      nYrObs: 10.0 # number of years of observations

    # params for Euclid errors
    euclid:
      bandNames:
        ey: ey
        j: j
        h: h
      nYrObs: 1.0 # assume Euclid is point-and-stare, so don't coadd
      nVisYr: # assume Euclid is point-and-stare, so don't coadd
        ey: 1.0
        j: 1.0
        h: 1.0
      m5: # coadded 5-sig limiting mags, from https://arxiv.org/abs/2004.07885
        ey: 24.0
        j: 24.2
        h: 23.9
      gamma: # band dependent err param, from https://arxiv.org/abs/2004.07885
        ey: 0.04
        j: 0.04
        h: 0.04
      sigmaSys: 0.005 # expected irreducible error

  # apply minimum SNR cuts
  SNR_cuts:
    u: 1.0
    g: 1.0
    r: 1.0
    i: 5.0
    z: 1.0
    y: 1.0
    ey: 1.0
    j: 1.0
    h: 1.0

# ---------------------------
# settings for the ensembles
# ---------------------------
ensembles:
  N_train: 100_000 # number of galaxies in the training set
  N_test: 20_000 # number of galaxies in the test set
  N_flows: 10 # number of flows per ensemble

# ----------------------
# settings for plotting
# ----------------------
plotting:
  rcParams:
    font.size: 10
    axes.titlesize: 10
    axes.labelsize: 10

  forest_spectra:
    format: pdf
  W_vs_NHI:
    format: png
  du_tau_hist:
    format: pdf
